=== gaudenzioyang-commits/f1-metadata-schema/f1_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.org/f1/schema/"
           xmlns:f1="http://example.org/f1/schema/"
           xmlns:dcterms="http://purl.org/dc/terms/"
           elementFormDefault="qualified">

    <xs:import namespace="http://purl.org/dc/terms/" 
               schemaLocation="https://www.dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd"/>

    <xs:simpleType name="PositionType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([1-9]|1[0-9]|20|DNF|DNS|DSQ)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="StintType">
        <xs:sequence>
            <xs:element name="TireCompound" type="xs:string"/>
            <xs:element name="Laps" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DriverRecordType">
        <xs:sequence>
            <xs:element name="DriverName" type="xs:string"/>
            <xs:element name="Team" type="xs:string"/>
            <xs:element name="Position" type="f1:PositionType"/>
            <xs:element name="Stint" type="f1:StintType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="RaceRecord">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dcterms:title"/>
                <xs:element ref="dcterms:date"/>
                <xs:element name="Circuit" type="xs:string"/>
                <xs:element name="DriverRecord" type="f1:DriverRecordType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gaudenzioyang-commits/f1-metadata-schema/race_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<f1:RaceRecord xmlns:f1="http://example.org/f1/schema/"
               xmlns:dcterms="http://purl.org/dc/terms/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://example.org/f1/schema/ https://gaudenzioyang-commits.github.io/f1-metadata-schema/f1_schema.xsd">

    <dcterms:title>2024 Bahrain Grand Prix Race Results</dcterms:title>
    <dcterms:date>2024-03-02</dcterms:date>
    <f1:Circuit>Bahrain International Circuit</f1:Circuit>
    
    <f1:DriverRecord>
        <f1:DriverName>Max Verstappen</f1:DriverName>
        <f1:Team>Red Bull Racing</f1:Team>
        <f1:Position>1</f1:Position>
        <f1:Stint>
            <f1:TireCompound>Soft</f1:TireCompound>
            <f1:Laps>17</f1:Laps>
        </f1:Stint>
        <f1:Stint>
            <f1:TireCompound>Hard</f1:TireCompound>
            <f1:Laps>40</f1:Laps>
        </f1:Stint>
    </f1:DriverRecord>

    <f1:DriverRecord>
        <f1:DriverName>Charles Leclerc</f1:DriverName>
        <f1:Team>Ferrari</f1:Team>
        <f1:Position>DNF</f1:Position>
        <f1:Stint>
            <f1:TireCompound>Soft</f1:TireCompound>
            <f1:Laps>15</f1:Laps>
        </f1:Stint>
    </f1:DriverRecord>
    
</f1:RaceRecord>
